"""Added SourcesORM ResumesORM KeywordsResumesORM resume_source_association  tables

Revision ID: b6a928a39b57
Revises: 11dc0a56a5fa
Create Date: 2026-09-17 23:29:27.450038

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6a928a39b57"
down_revision: str | Sequence[str] | None = "11dc0a56a5fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("resumes",
    sa.Column("name", sa.String(length=255), nullable=False),
    sa.Column("text", sa.Text(), nullable=False),
    sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_resumes"))
    )
    op.create_table("sources",
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column("code", sa.String(length=20), nullable=False),
    sa.Column("base_url", sa.String(), nullable=False),
    sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    sa.UniqueConstraint("code", name=op.f("uq_sources_code"))
    )
    op.create_table("keywords_resumes",
    sa.Column("keyword", sa.String(length=100), nullable=False),
    sa.Column("resume_id", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(["resume_id"], ["resumes.id"], name=op.f("fk_keywords_resumes_resume_id_resumes")),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_keywords_resumes"))
    )
    op.create_table("resume_source_association",
    sa.Column("resume_id", sa.Integer(), nullable=False),
    sa.Column("source_id", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(["resume_id"], ["resumes.id"], name=op.f("fk_resume_source_association_resume_id_resumes")),
    sa.ForeignKeyConstraint(["source_id"], ["sources.id"], name=op.f("fk_resume_source_association_source_id_sources")),
    sa.PrimaryKeyConstraint("resume_id", "source_id", name=op.f("pk_resume_source_association"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resume_source_association")
    op.drop_table("keywords_resumes")
    op.drop_table("sources")
    op.drop_table("resumes")
    # ### end Alembic commands ###
